always-replace-config: true

join-messages:
  - "<green>%player% joined the game"
  - "<green>%player% popped out of nowhere"
  - "<green>%player% has returned from their soul mission"
  - "<green>%player% didn't end themself while offline"
  - "<green>%player% has come to save the world"
  - "<green>%player% has come to annoy everyone"
  - "<green>%player% got their popcorn"
  - "<green>%player% wants to eat some steak"
  - "<green>%player% is ready to die"
  - "<green>%player% decided to like frogs too much"
  - "<green>%player% loves somebody probably!"
  - "<green>%player% thinks that minecraft is boring and yet they play it"
  - "<green>%player% kissed a grandma"
  - "<green>%player% kissed a grandpa"
  - "<green>%player% licked a stone in the ground"
  - "<green>%player% eyed a cow in a way"
  - "<green>%player% drank some battery acid"
  - "<green>%player% came back from their mission. They had to save 50 cows, 10 chickens, 13 donkeys, 482 bees, 32 elephants, 93 pigs, 273 blue whales, 69 humans, 72 boats, 2321 ants, 12 dogs, 203 cats from a burning building"
  - "<green>%player% has given some thought to living their best life they can"
  - "<green>%player% likes likes somebody"
  - "<green>%player% is now married"
  - "<green>%player% is now divorced"
  - "<green>%player% is thinking about boys"
  - "<green>%player% is thinking about girls"
  - "<green>%player% is thinking about how dogs and humans are compatible, but not in a bad way"
  - "<green>%player% has come to steal some items"
  - "<green>%player% has come to give back items"
  - "<green>%player% likes licking rocks"
  - "<green>%player% likes boys"
  - "<green>%player% IS READY TO JUMP OFF A CLIFF"
  - "<green>%player% is ready to trade pokemon cards with anyone"
  - "<green>%player% is here to manage the server"
  - "<green>%player% dislikes cats"
  - "<green>%player% has issues with someone online"
  - "<green>%player% eats rocks"
  - "<green>%player% has a AI girlfriend"
  - "<green>%player% has a AI boyfriend"
  - "<red>%player% got a red join message!"
  - "<yellow>%player% got a yellow join message!"
  - "<rainbow>%player% got a rainbow join message!"
  - "<rainbow:3>%player% got a rainbow join message!"
  - "<green>%player% fucked"
  - "<green>%player% likes star wars"
  - "<green>%player% drinks red bull energy drink"
  - "<green>%player% eats satsumas"
  - "<green>%player% is THE walter white"
  - "<green>%player% can't sit still for 10 minutes"
  - "<green>%player% is going to complain about something soon"
  - "<green>%player% is about to bust"
  - "<green>%player% is about to jump off a cliff"
  - "<green>%player% closed their AI girlfriends servers"
  - "<green>%player% closed their AI boyfriends servers"
  - "<green>%player% is into some bunny action (feeding them)"
  - "<green>%player% likes bunnies"
  - "<green>%player% has a house underground"
  - "<green>%player% has a super good looking boyfriend"
  - "<green>%player% has a super good looking girlfriend"
  - "<green>%player% has a chicken named cow"
  - "<green>%player% is a chicken"
  - "<green>%player% is a <rainbow>rainbow sexual"
  - "<green>%player% is going to kill somebody"
  - "<green>%player% is going to have a bad acne"
  - "<green>%player% has a bad acne"
  - "<green>%player% ate a bar of chocolate"
  - "<green>%player% put their di- I mean flour in a locked barrel"
  - "<green>%player% is a girl"
  - "<green>%player% is a boy"
  - "<green>%player% likes placenta pills too much"
  - "<green>%player% is going to eat some eat placenta pills"
  - "<green>%player% is going to kill themselves"
  - "<green>%player% is going to die alone"
  - "<green>%player%'s mom is being drained by the plumber"
  - "<green>%player%'s dad is the plumber"
  - "<green><bold>+ <green>%player%"
  - "<green>%player% is the guardian of the galaxy"
  - "<green>%player% is into pussy cats"
  - "<green>%player% has bought an annoying cock to the farm which keeps on yelling fap fap."
  - "<green>%player% makes the fap fap sounds"
  - "<green>%player% is dumb."
  - "<#FFC0CB>%player% likes the color pink"

quit-messages:
 - "<red>%player% left the game"
 - "<red>%player% left to get popcorn"
 - "<red>%player% rage quit"
 - "<red>%player% wanted the easy way out"
 - "<red>%player% got psychedelic and left"
 - "<red>%player% didn't want to play anymore"
 - "<red>%player% didn't like the company they had"
 - "<red>%player% got a frog fetish and left the game"
 - "<red>%player% left to eat some cream"
 - "<red>%player% didn't enjoy playing"
 - "<red>%player% decided to get a life"
 - "<red>%player% left to kiss a grandma"
 - "<red>%player% left to kiss a grandpa"
 - "<red>%player% thinks that the next person to leave is dumb"
 - "<red>%player% is eating now"
 - "<red>%player% doesn't realize how large the world is"
 - "<red>%player% doesn't want to be here"
 - "<red>%player% loves herself"
 - "<red>%player% has real life issues and went to fix them"
 - "<red>%player% had to go shoot something"
 - "<red>%player% had to check something"
 - "<red>%player% liked rocks too much and left"
 - "<red>%player% inherited their grandpa's grandma"
 - "<red>%player% had a stroke"
 - "<red>%player% refused to play anymore"
 - "<red>%player% left to survive their parents wrath"
 - "<red>%player% has estimated 10 seconds to come back"
 - "<red>%player% had to go reassure their mom to let them play 5 more minutes"
 - "<red>%player% had to go decide what to wear for tomorrow"
 - "<red>%player% had to go lose pennies"
 - "<red>%player% tried to copy superman"
 - "<red>%player% left to ask a favor"
 - "<red>%player% quit"
 - "<red>%player% had to go decide which wedding ring to buy"
 - "<red>%player% suppress the media"
 - "<red>%player% had to clear their mind"
 - "<red>%player% wastes diamonds on diamond hoes"
 - "<red>%player% wasted"
 - "<red>%player% clung on to a cow"
 - "<red>%player% has decided to go marry somebody"
 - "<red>%player% has decided to go marry a random person from the streets"
 - "<red>%player% has decided to go divorced their wife"
 - "<red>%player% has decided to go divorced their husband"
 - "<red>%player% froze to death"
 - "<red>%player% is trying to sustain their life"
 - "<red>%player% left to wander around"
 - "<red>%player% needed to feed the cats"
 - "<red>%player% is gonna close their AI girlfriend's servers"
 - "<red>%player% is gonna close their AI boyfriend's servers"
 - "<red>%player% broke the locked barrel and no longer has a di- nvm"
 - "<red>%player% just left to get ice cream"

links:
  - "https://"
  - "http://"

chat-format: "<white>%player%<gray>:<white> %message%"
chat-item-format: "<yellow>%amount%x<white> %displayname%"
chat-item-air-format: "<yellow><hover:show_text:'<!italic><green>Nothing to see here!'>%player%'s hand"

sleep:
  1: 1
  2: 1
  3: 1
  4: 1
  5: 2
  6: 2
  7: 2
  8: 2
  9: 2
  10: 2
  11: 2
  12: 2
  13: 3
  14: 3
  15: 3
  16: 3
  17: 3
  18: 3
  19: 3